<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Code</label>

	<div class="col-sm-10">
		<input type="text"  class="form-control" readonly  placeholder="Auto Generated by System" value="<?php echo (isset($class_code)) ? $class_code : null ?>">
	</div>
</div>
<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Class Name</label>

	<div class="col-sm-10">
		<input type="text" name="class_name" class="form-control"  placeholder="Class Name" value="<?php echo (isset($class_name)) ? $class_name : null ?>" >
	</div>
</div>
<div class="form-group">
	<label for="email" class="col-sm-2 control-label">Academic Year</label>
	<div class="col-sm-4">
		<input type="number" min="<?php echo date('Y') ?>" name="ay_start" class="form-control" placeholder="Year Start" value="<?php echo (isset($class_start_ay)) ? $class_start_ay : null ?>">
	</div>
	<div class="col-sm-2 text-center">
		/
	</div>
	<div class="col-sm-4">
		<input type="number" min="<?php echo date('Y')+1 ?>" name="ay_end" class="form-control" placeholder="Year End" value="<?php echo (isset($class_end_ay)) ? $class_end_ay : null ?>">
	</div>
</div>
<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Grade</label>
	<div class="col-sm-10">
		<select name="grade" id="" class="form-control">
			<option value="" selected disabled>Select Grade</option>
			<?php $grades = 1; ?>
			<?php while($grades<13){ ?>
				<option <?php if(isset($class_grade)){ if($class_grade == $grades){ echo "selected";} } ?>  value="<?php echo $grades ?>"><?php echo $grades ?></option>
			<?php $grades++;}?> 
		</select>
	</div>
</div>
<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Homeroom</label>
	<div class="col-sm-10">
		<select name="homeroom" class="form-control">
			<option selected disabled>Select Homeroom</option>
			<?php foreach($homerooms as $item){ ?>
			<option <?php if(isset($class_homeroom_id)){ if($item->id == $class_homeroom_id){ echo "selected";} } ?> value="<?php echo $item->id ?>"><?php echo $item->name?></option>
			<?php } ?>
		</select>
	</div>
</div>
<div class="form-group">
	<label for="name" class="col-sm-2 control-label">Department</label>

	<div class="col-sm-10">
		<select name="department" id="" class="form-control">
			<option selected disabled>Select Department</option>
			<?php foreach($departments as $item){ ?>
			<option <?php if(isset($class_department_id)){ if($item->department_id == $class_department_id){ echo "selected";} } ?> value="<?php echo $item->department_id ?>"><?php echo $item->department_name ?></option>
			<?php } ?>
		</select>
	</div>
</div>
